HttpServer:
  Port: ":8081"
  PprofPort: ":8100"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  CookieLifeTime: 44640
  SessionCookieName: "session_token"

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

mysql:
  Host: localhost
  Port: 5432
  User: postgres
  Password: 123
  Dbname: postgres

firebase:
  Path: "./test.json"  